import base64

from .common import FinanceTestCommon

# A hand-authored fixture based on Tally's published XML voucher schema
# (ENVELOPE/HEADER/BODY/IMPORTDATA/REQUESTDATA/TALLYMESSAGE/VOUCHER with
# ALLLEDGERENTRIES.LIST) - NOT generated by this module's own export.
# A round-trip-only test (export your own XML, re-import it) would pass
# even if the format didn't match anything external; this fixture is the
# check that actually exercises the real schema.
HAND_AUTHORED_TALLY_XML = """<?xml version="1.0" encoding="UTF-8"?>
<ENVELOPE>
  <HEADER>
    <TALLYREQUEST>Import Data</TALLYREQUEST>
  </HEADER>
  <BODY>
    <IMPORTDATA>
      <REQUESTDESC>
        <REPORTNAME>Vouchers</REPORTNAME>
      </REQUESTDESC>
      <REQUESTDATA>
        <TALLYMESSAGE xmlns:UDF="TallyUDF">
          <VOUCHER VCHTYPE="Sales" ACTION="Create">
            <DATE>20260615</DATE>
            <VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>
            <VOUCHERNUMBER>TALLY-INV-001</VOUCHERNUMBER>
            <PARTYLEDGERNAME>{customer}</PARTYLEDGERNAME>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{customer}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
              <AMOUNT>5000.00</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{income_account}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
              <AMOUNT>5000.00</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
          </VOUCHER>
          <VOUCHER VCHTYPE="Purchase" ACTION="Create">
            <DATE>20260616</DATE>
            <VOUCHERTYPENAME>Purchase</VOUCHERTYPENAME>
            <VOUCHERNUMBER>TALLY-PUR-001</VOUCHERNUMBER>
            <PARTYLEDGERNAME>Some Vendor Not In Odoo</PARTYLEDGERNAME>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>Some Vendor Not In Odoo</LEDGERNAME>
              <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
              <AMOUNT>2000.00</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{expense_account}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
              <AMOUNT>2000.00</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
          </VOUCHER>
        </TALLYMESSAGE>
      </REQUESTDATA>
    </IMPORTDATA>
  </BODY>
</ENVELOPE>
"""


class TestTallyExportImportRoundTrip(FinanceTestCommon):
    def test_export_then_import_recreates_the_same_voucher_count(self):
        self._post_customer_invoice(1000.0, "2026-06-01", due_date="2026-06-01")
        self._post_customer_invoice(2000.0, "2026-06-05", due_date="2026-06-05")

        export = self.env["bpro.tally.export.batch"].create(
            {"date_from": "2026-06-01", "date_to": "2026-06-30"}
        )
        export.action_export()
        self.assertEqual(export.state, "done")
        self.assertEqual(export.voucher_count, 2)
        self.assertTrue(export.xml_file)

        import_batch = self.env["bpro.tally.import.batch"].create(
            {"xml_file": export.xml_file, "xml_filename": export.xml_filename}
        )
        import_batch.action_import()
        self.assertEqual(import_batch.state, "done")
        self.assertEqual(import_batch.imported_count, 2)
        self.assertFalse(import_batch.exception_ids)


UNBALANCED_VOUCHER_AMONG_VALID_ONES = """<?xml version="1.0" encoding="UTF-8"?>
<ENVELOPE>
  <BODY>
    <IMPORTDATA>
      <REQUESTDATA>
        <TALLYMESSAGE>
          <VOUCHER VCHTYPE="Journal" ACTION="Create">
            <DATE>20260601</DATE>
            <VOUCHERTYPENAME>Journal</VOUCHERTYPENAME>
            <VOUCHERNUMBER>TALLY-UNBALANCED-001</VOUCHERNUMBER>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{cash}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
              <AMOUNT>500.00</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{income}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
              <AMOUNT>499.00</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
          </VOUCHER>
          <VOUCHER VCHTYPE="Journal" ACTION="Create">
            <DATE>20260602</DATE>
            <VOUCHERTYPENAME>Journal</VOUCHERTYPENAME>
            <VOUCHERNUMBER>TALLY-VALID-AFTER-001</VOUCHERNUMBER>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{cash}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
              <AMOUNT>300.00</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{income}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
              <AMOUNT>300.00</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
          </VOUCHER>
        </TALLYMESSAGE>
      </REQUESTDATA>
    </IMPORTDATA>
  </BODY>
</ENVELOPE>
"""


class TestTallyImportSurvivesAPerVoucherFailure(FinanceTestCommon):
    def test_unbalanced_voucher_becomes_exception_not_a_crash(self):
        # Reproduces a real failure hit against an actual client export
        # (8127 real vouchers): one unbalanced entry used to raise
        # UserError out of account.move.create() itself, uncaught by the
        # try/except that only wrapped action_post() - crashing the whole
        # batch instead of logging just that one voucher, and (without a
        # savepoint) leaving the cursor's transaction aborted so every
        # subsequent voucher - even valid ones - would fail too.
        cash = self.env["account.account"].search(
            [("company_ids", "in", self.company.id), ("account_type", "=", "asset_cash")],
            limit=1,
        )
        income = self.env["account.account"].search(
            [("company_ids", "in", self.company.id), ("account_type", "=", "income")],
            limit=1,
        )
        self.assertTrue(cash and income, "test CoA must have cash/income accounts")

        xml_text = UNBALANCED_VOUCHER_AMONG_VALID_ONES.format(
            cash=cash.name, income=income.name
        )
        import_batch = self.env["bpro.tally.import.batch"].create(
            {
                "xml_file": base64.b64encode(xml_text.encode("utf-8")),
                "xml_filename": "unbalanced_fixture.xml",
            }
        )
        import_batch.action_import()

        self.assertEqual(import_batch.state, "done")
        self.assertEqual(
            import_batch.imported_count,
            1,
            "the valid voucher after the bad one must still import - the "
            "batch must not abort or silently drop it",
        )
        self.assertEqual(len(import_batch.exception_ids), 1)
        self.assertEqual(
            import_batch.exception_ids.voucher_number, "TALLY-UNBALANCED-001"
        )

        posted = self.env["account.move"].search(
            [("ref", "=", "TALLY-VALID-AFTER-001")]
        )
        self.assertEqual(posted.state, "posted")
        broken = self.env["account.move"].search(
            [("ref", "=", "TALLY-UNBALANCED-001")]
        )
        self.assertFalse(
            broken, "the failed voucher must not leave a half-created draft move behind"
        )


class TestTallyImportHandAuthoredFixture(FinanceTestCommon):
    def test_valid_voucher_imports_unmapped_ledger_becomes_exception(self):
        income_account = self.env["account.account"].search(
            [
                ("company_ids", "in", self.company.id),
                ("account_type", "=", "income"),
            ],
            limit=1,
        )
        expense_account = self.env["account.account"].search(
            [
                ("company_ids", "in", self.company.id),
                ("account_type", "=", "expense"),
            ],
            limit=1,
        )
        self.assertTrue(income_account and expense_account, "test CoA must have income/expense accounts")

        xml_content = HAND_AUTHORED_TALLY_XML.format(
            customer=self.customer.name,
            income_account=income_account.name,
            expense_account=expense_account.name,
        )
        import_batch = self.env["bpro.tally.import.batch"].create(
            {
                "xml_file": base64.b64encode(xml_content.encode("utf-8")),
                "xml_filename": "hand_authored_fixture.xml",
            }
        )
        import_batch.action_import()

        self.assertEqual(
            import_batch.imported_count,
            1,
            "the Sales voucher (known customer + known income ledger) must import",
        )
        self.assertEqual(len(import_batch.exception_ids), 1)
        self.assertIn(
            "Some Vendor Not In Odoo", import_batch.exception_ids.reason
        )

        posted = self.env["account.move"].search(
            [("ref", "=", "TALLY-INV-001")]
        )
        self.assertEqual(posted.state, "posted")
        # imported as a generic journal entry (move_type='entry'), so check
        # the actual debit total rather than amount_total, which is
        # computed for invoice-type moves, not plain journal entries
        self.assertEqual(sum(posted.line_ids.mapped("debit")), 5000.0)
