from . import hr_applicant
from . import hr_employee
from . import res_company
from . import bpro_employee_asset
from . import bpro_interview_evaluation
from . import bpro_job_offer
from . import bpro_joining_report
from . import bpro_vacancy_request
from . import bpro_vacancy_request_reject_wizard
